### ISSUE TITLE
Unable to locate /modem Partition

### ISSUE THREAD

**Issue by janssenb** [TeamWin/android_device_lge_d855#1]
Many Thanks for this, just flashed and now performing a backup and got the message :-

E: Unable to locate '/modem' partition for backup calculations

Backing up Boot...
Backing up System...
Backing up Data...
Backing up Cache...
E: Unable to locate '/modem' partition for backup process.
Backing up EFS...
Backing up efs2...
Updating partition tables
...done
[BACKUP COMPLETED IN 124 SECONDS]

Any idea why the modem partition is not being backed up...? 
Version 2.8.3.0

**Comment by ZjemCiKolege** [comment]
Old bug can be closed
