### ISSUE TITLE
Recovery Build Version 3.0.2.0

### ISSUE THREAD

**Issue by GendoIkari** [TeamWin/android_device_lge_d855#4]
Hi! I really need the last version of Recovery for the d855. I saw on jenkins (https://jenkins.twrp.me/) that the build for the d855 was successful with exactly the last version, but there was an error in the rsync for the deploy.
Is it possible to have an official release (on the official site) of this version? Are there any problems about not having the last version on the d855?

Thank you for the courtesy!

**Comment by bigbiff** [comment]
Thanks for the heads up. I have fixed the job.
